version: '3.8'

services:
  web:
    build: .
    container_name: reobote-web
    restart: always
    expose:
      - "8080"
    environment:
      - DATABASE_URL=postgresql://root:kZ7oYab65fQITbyPPV6CLgrL5NIONpwZ@postgres:5432/reoboteconsorcios
      - API_URL=https://api.agendor.com.br/v3/deals
      - API_TOKEN=Token 79e07232-4035-4b77-8808-2a9540585c54
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboardreobote.rule=Host(`dashboard.reoboteconsorcios.com.br`)
      - traefik.http.routers.dashboardreobote.entrypoints=websecure
      - traefik.http.routers.dashboardreobote.tls.certresolver=le
      - traefik.http.routers.dashboardreobote.service=dashboardreobote
      - traefik.http.services.dashboardreobote.loadbalancer.server.port=8080
      - traefik.http.services.dashboardreobote.loadbalancer.passHostHeader=true
    networks:
      - traefik_public
      - network_public

networks:
  traefik_public:
    external: true
  network_public:
    external: true
